// Next.js API route support: https://nextjs.org/docs/api-routes/introduction
let dummyData = [
  {
    img: "android.webp",
    description:
      "it is lit Lorem ipsum dolor sit amet consectetur adipisicing elit. Delectus accusamus quas aspernatur non consectetur nisi? ",
    condition: "new",
    price: 6,
    productName: "android1",
    inStock: 6,
  },
  {
    img: "beuty.jfif",
    description: "it is lit",
    condition: "new",
    price: 3,
    productName: "cosmetics2",
    inStock: 7,
  },
  {
    img: "clothings.jfif",
    description: "it is lit",
    condition: "new",
    price: 40,
    productName: "fashion3",
    inStock: 6,
  },
  {
    img: "clothings2.jfif",
    description: "it is lit",
    condition: "new",
    price: 6,
    productName: "clothes4",
    inStock: 6,
  },
  {
    img: "clothings3.jfif",
    description: "it is lit",
    condition: "new",
    price: 6,
    productName: "clothes5",
    inStock: 6,
  },
  {
    img: "clothings4.jfif",
    description: "it is lit",
    condition: "new",
    price: 88,
    productName: "clothes6",
    inStock: 7,
  },
  {
    img: "fashion1.jfif",
    description: "it is lit",
    condition: "new",
    price: 6,
    productName: "android7",
    inStock: 6,
  },
  {
    img: "fashion2.jfif",
    description: "it is lit",
    condition: "new",
    price: 6,
    productName: "android8",
    inStock: 6,
  },
  {
    img: "fashion3.jfif",
    description: "it is lit",
    condition: "new",
    price: 6,
    productName: "android9",
    inStock: 6,
  },
  {
    img: "fashion4.jfif",
    description: "it is lit",
    condition: "new",
    price: 6,
    productName: "fashion10",
    inStock: 6,
  },
  {
    img: "fashion5.jfif",
    description: "it is lit",
    condition: "new",
    price: 6,
    productName: "fashion11",
    inStock: 6,
  },
  {
    img: "fashions.jfif",
    description: "it is lit",
    condition: "new",
    price: 6,
    productName: "13",
    inStock: 6,
  },
  {
    img: "shoes.jfif",
    description: "it is lit",
    condition: "second hand ",
    price: 6,
    productName: "shoes14",
    inStock: 6,
  },
  {
    img: "shoes2.jfif",
    description: "it is lit",
    condition: "new",
    price: 6,
    productName: "shoes15",
    inStock: 6,
  },
  {
    img: "shoes3.jfif",
    description: "it is lit",
    condition: "new",
    price: 6,
    productName: "shoes16",
    inStock: 6,
  },
  {
    img: "headsets.jfif",
    description: "it is lit",
    condition: "new",
    price: 6,
    productName: "headsets17",
    inStock: 6,
  },
];
let stores = [
  {
    img: "watch.jfif",
    description: "it is lit",
    available: "6 to 12pm",
    storeName: "headsets store18",
    storeOwner: "joseph",
  },
  {
    img: "iphone.jfif",
    description: "it is lit",
    available: "6 to 12pm",
    storeName: "phone store19",
    storeOwner: "joseph",
  },
  {
    img: "watch.jfif",
    description: "it is lit",
    available: "6 to 12pm",
    storeName: "headsets store20",
    storeOwner: "joseph",
  },
  {
    img: "watch.jfif",
    description: "it is lit",
    available: "6 to 12pm",
    storeName: "headsets store 21",
    storeOwner: "joseph",
  },
  {
    img: "watch.jfif",
    description: "it is lit",
    available: "6 to 12pm",
    storeName: "headsets store",
    storeOwner: "joseph",
  },
  {
    img: "watch.jfif",
    description: "it is lit",
    available: "6 to 12pm",
    storeName: "headsets store",
    storeOwner: "joseph",
  },
  {
    img: "watch.jfif",
    description: "it is lit",
    available: "6 to 12pm",
    storeName: "headsets store",
    storeOwner: "joseph",
  },
  {
    img: "watch.jfif",
    description: "it is lit",
    available: "6 to 12pm",
    storeName: "headsets store",
    storeOwner: "joseph",
  },
  {
    img: "watch.jfif",
    description: "it is lit",
    available: "6 to 12pm",
    storeName: "headsets store",
    storeOwner: "joseph",
  },
  {
    img: "iphone.jfif",
    description: "it is lit",
    available: "6 to 12pm",
    storeName: "phone store",
    storeOwner: "joseph",
  },
  {
    img: "iphone.jfif",
    description: "it is lit",
    available: "6 to 12pm",
    storeName: "phone store",
    storeOwner: "joseph",
  },
  {
    img: "iphone.jfif",
    description: "it is lit",
    available: "6 to 12pm",
    storeName: "phone store",
    storeOwner: "joseph",
  },
];
export default function handler(req, res) {
  res.status(200).json({ products: dummyData, stores: stores });
}
